# Generated by Django 4.1.7 on 2023-08-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
