# Generated by Django 4.1.4 on 2023-08-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_visitor_cookie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
