# Generated by Django 4.1.4 on 2023-08-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_remove_addrooms_bathroom_remove_addrooms_bed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
