# Generated by Django 4.1.4 on 2023-08-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_remove_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
