# Generated by Django 4.1.4 on 2023-08-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_remove_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_namess', models.CharField(max_length=255)),
                ('contact_emails', models.EmailField(max_length=255)),
                ('contact_subjects', models.CharField(max_length=50000)),
                ('contact_messages', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1),
        ),
    ]
