# Generated by Django 4.1.4 on 2023-08-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_contact_us_info_alter_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(blank=True, max_length=255)),
                ('slide_image', models.ImageField(blank=True, null=True, upload_to='picture10')),
                ('slide_words', models.CharField(blank=True, max_length=255)),
                ('about_us_images', models.ImageField(blank=True, null=True, upload_to='picture20')),
                ('about_us_words', models.CharField(blank=True, max_length=255)),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('twitter', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
